INSERT INTO STUDENT(NAME,AGE,ADDRESS) VALUES('Zhang Liang', 27,'CHENGDU')
INSERT INTO STUDENT(NAME,AGE,ADDRESS) VALUES('SHEN ZHANG', 28,'CHENGDU CITY')
INSERT INTO STUDENT(NAME,AGE,ADDRESS) VALUES('MA WEI', 29,'CHENGDU CITY, SICHUAN PROVINCE')